## If not running interactively, don't do anything
[ -z "${PS1}" ] && return

## 256 colors
echo "$TERM" | grep -q "256color" || export TERM=xterm-256color

## Custom PATH
test -f "$HOME/.custompath" && source "$HOME/.custompath"

## Raid statux
if test -f /proc/mdstat; then
	echo "============================  Raid Status  ================================"
	egrep --color -A1 "^md[0-9]+" /proc/mdstat
	echo "==========================================================================="
fi
true

