set nocompatible
execute pathogen#infect()
syntax on
filetype plugin indent on


"" Color
set background=dark 
colorscheme essembeh
syntax on

"" File encoding
set encoding=utf-8
set fileencoding=utf-8 

"" Tab parameters
set tabstop=4
set shiftwidth=4
set noexpandtab

"" Indentation
"set cindent
"set autoindent
set smartindent

" General settings
set showmatch                    " verifications des {} () []
set incsearch                    " Recherche pendant la recherche
set hlsearch                     " Highlight search
set smartcase                    " recherche selon la casse la plus approchante
set ruler                        " afficher la position
set showcmd                      " affiche les commandes incomplète 
set backspace=indent,eol,start   " autorisation du retour arrière

"" Mouse
"set mouse=a
"set ttymouse=xterm2

"" Saving
"set autowrite                    " sauvegarder à chaque :make & :next
set updatecount=0                " pas de fichier de secours


"" VARIABLES
let g:GPGPreferSymmetric=1
let g:GPGUsePipes=1

"" ALIAS

"" CTRL+L to show line numbers
imap <C-l>  <esc>:set nu<cr>i
map  <C-l>  :set nu<cr>

"" unhiglight search on ENTER
nnoremap <silent> <cr>  :nohlsearch<Bar>:echo<CR>

map <C-n> :NERDTreeToggle<CR>
