set nocompatible
execute pathogen#infect()
syntax on
filetype plugin indent on


"" Color
set background=dark 
colorscheme essembeh
syntax on

"" File encoding
set encoding=utf-8
set fileencoding=utf-8 

"" Tab parameters
set tabstop=4
set shiftwidth=4
set noexpandtab

"" Indentation
"set cindent
"set autoindent
set smartindent

" General settings
set showmatch " Verifications des {} () []
set hlsearch " Highlight search
set smartcase " recherche selon la casse la plus approchante
set ruler " afficher la position
set showcmd " affiche les commandes incomplète 
set laststatus=2
set virtualedit=onemore " Allow for cursor beyond last character
set history=1000 " Store a ton of history (default is 20)
set hidden " Allow buffer switching without saving
"set spell " Spell checking on

"" Mouse
"set mouse=a
"set ttymouse=xterm2

"" Saving
"set autowrite " sauvegarder à chaque :make & :next
set updatecount=0 " pas de fichier de secours


"" VARIABLES
let g:GPGPreferSymmetric=1
let g:GPGUsePipes=1
let g:airline#extensions#tabline#enabled=1
let g:airline_theme='luna' 

"" ALIAS

"" CTRL+L to show line numbers
imap <C-l> <esc>:set nu<cr>i
map <C-l> :set nu<cr>
map <C-p> :bprev<cr>
map <C-n> :bnext<cr>

"" unhiglight search on ENTER
nnoremap <silent> <cr> :nohlsearch<Bar>:echo<CR>

"" Nerd Tree
map <C-t> :NERDTreeToggle<CR>
