## 256 colors
export TERM=xterm-256color

# Colors for ls
test "$LS_COLORS" = "" && which dircolors > /dev/null 2>&1 && eval `dircolors`

## Custom PATH
test -f "$HOME/.custompath" && eval `cat "$HOME/.custompath"`

## Raid statux
if test -f /proc/mdstat; then
	echo "============================  Raid Status  ================================"
	egrep --color -A1 "^md[0-9]+" /proc/mdstat
	echo "==========================================================================="
fi
true

